######################################################################
# Automatically generated by qmake (2.01a) ? 12 22 09:39:36 2015
######################################################################

TEMPLATE = lib
CONFIG += plugin

#TARGET = 
#DEPENDPATH += .
#INCLUDEPATH += .

# Input
HEADERS = ../font_length_app/LengthCalculationInterface.h LengthCalculationDummy8.h
SOURCES = LengthCalculationDummy8.cpp
DESTDIR = ../font_length_app/plugins
