######################################################################
# Automatically generated by qmake (2.01a) ? 12 22 13:00:23 2015
######################################################################

TEMPLATE = app
#TARGET = 
#DEPENDPATH += .
#INCLUDEPATH += .

# Input
HEADERS = FontDialog.h LengthCalculationInterface.h 
SOURCES = main.cpp FontDialog.cpp
FORMS = FontLengthApp.ui
